# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d03f6d793757cc8c25d19c85dab84491dddb017f5f0052056cce028b0f2e24b71830a79036b80374d186781f4612e1294145130942914459972e0178c7f53a6

test:
  secret_key_base: 7156ae32bc65b7bf92c692d300e4c837d5f5a2046b0e6326bef0ce967588db9d2a368450c3fa7000be572de41af43368ee21c5dcb228d1cf614052b213d55bc5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
